### ISSUE TITLE
Com exception in 3ds Max 2022

### ISSUE THREAD

**Issue by dlightme** [JeffHanna/MXSPyCOM#21]
I'm trying to get the MXSPYCom server to execute scripts in 3ds Max 2022 (Python 3.7)
With initialize_COM_server in %appData%\Local\Autodesk\3dsMax\2022 - 64bit\ENU\scripts\startup launching from PyCharm, Notepad++ or cmd results in 

C:\Users\xxxxx\MXSPyCOM>MXSPyCOM.exe -f "C:\test.py"
Unhandled exception. System.Runtime.InteropServices.COMException (0x80020006): Unknown name. (0x80020006 (DISP_E_UNKNOWNNAME))
   at System.RuntimeType.InvokeDispMethod(String name, BindingFlags invokeAttr, Object target, Object[] args, Boolean[] byrefModifiers, Int32 culture, String[] namedParameters)
   at System.RuntimeType.InvokeMember(String name, BindingFlags bindingFlags, Binder binder, Object target, Object[] providedArgs, ParameterModifier[] modifiers, CultureInfo culture, String[] namedParams)
   at MXSPyCOM.Program.execute_max_commands(String[] args, String filepath)
   at MXSPyCOM.Program.Main(String[] args)
   
I've tried every variation of pathnames (single, double, no quotes, /, //, \ ) it's always the same result. 
Is this compatible with 3ds Max 2022?

**Comment by JeffHanna** [comment]
Do you have safe script execution enabled? Sadly, at this time, you have to disable that for MXSPyCOM to work correctly.

**Comment by dlightme** [comment]
3ds max safe scene script execution was on, turned off, restart and same result. 0x80020006. Max 2022.3 Update (24.3.0.3404)

**Comment by Sugz** [comment]
I have the same problem, deactivating safe script execution didn't change anything. Max 2022.3.6 Security Fix (24.3.6.3521). Is there a solution now ?

**Comment by daniFM** [comment]
I'm having the same issue in Max 2024, but I didn't have the error in Max 2022 weirdly enough. Has anyone figured out a solution?
