### ISSUE TITLE
Unknown name

### ISSUE THREAD

**Issue by NTKKS** [JeffHanna/MXSPyCOM#22]
I get this when I run the task in VS CODE, what can I do?

Unhandled exception. System.Runtime.InteropServices.COMException (0x80020006): Neznámý název. (0x80020006 (DISP_E_UNKNOWNNAME))
   at System.RuntimeType.InvokeDispMethod(String name, BindingFlags invokeAttr, Object target, Object[] args, Boolean[] byrefModifiers, Int32 culture, String[] namedParameters)
   at System.RuntimeType.InvokeMember(String name, BindingFlags bindingFlags, Binder binder, Object target, Object[] providedArgs, ParameterModifier[] modifiers, CultureInfo culture, String[] namedParams)
   at MXSPyCOM.Program.execute_max_commands(String[] args, String filepath)
   at MXSPyCOM.Program.Main(String[] args)

**Comment by NTKKS** [comment]
I have changed my system and now everything works, just had to disable safe script execution
